[package]
name = "pepy-tech-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pepy_tech_stats"
crate-type = ["rlib"]

[[bin]]
name = "pepy-tech-stats"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
flexi_logger = "0.31.7"
futures = "0.3"
log = "0.4.29"
regex = "1.12.2"
reqwest = {version = "0.12.24", features = ["json"]}
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }


[profile.release]
opt-level = 2
lto = false
codegen-units = 256
panic = "abort"
strip = true
incremental = true



[lints.clippy]
pedantic = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
missing_errors_doc = "allow"

[dev-dependencies]
test-case = "3.3.1"
